namespace:
  name: sandbox

service:
  type: ClusterIP
  port: 3336
  targetPort: 5939
  protocol: TCP

image:
  repository: nashblade/techtrends
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 1

  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

containerPort: 5939

livenessProbe:
  path: /healthz
  port: 5939

readinessProbe:
  path: /healthz
  port: 5939
